name: Update Pins
on:
  repository_dispatch:
    types: [n8n-update]

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Pages rebuild
        run: curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
             -H "Accept: application/vnd.github.v3+json" \
             https://api.github.com/repos/${{ github.repository }}/pages/builds
